### PR TITLE
--add command: a complement to --clear

### PR DESCRIPTION
**Pull request by jpaugh**
--add command adds rules as opposed to --clear, which clears them. It
requires the whole rule to be specified as one argument to --add.

### CODE REVIEW

**Comment by mdipierro** [comment]
This is slightly confusing. --clear remove memory that a rule was executed therefore runs it again. It affects workflow.cache, not workflow.config.

--add instead edits workflow.config (not workflow.cache) and adds a line to it. --add is not the opposite of --clear.

I do not understand why you need it. If you want to add a rule to workflow.config,you can simply edit the file and add a line. You do not need to restart workflow.py. It will dynamically pick up the change and run the new rule. Similarly you can delete rules at runtime.

I am missing something?

**Comment by jpaugh** [comment]
Oh, I'm sorry. I didn't realize quite what clear was for. I assumed it meant to _delete_ a rule, and didn't check that assumption against the source.

**Comment by mdipierro** [comment]
Do you think we still need --add? Otherwise I will close it.

**Comment by jpaugh** [comment]
Since it's not actually the opposite of `--clear`, it doesn't make as much sense.

**Pull request closed without merging**
