### PR TITLE
Replace non-existing os.exit call.

### PR DESCRIPTION
**Pull request by rogererens**

### CODE REVIEW

**Comment by mdipierro** [comment]
Hello Roger, please email me so I know how to contact you. Also please feel to make a pull request to add yourself as an author/contributor in the README file.

**Comment by rogererens** [comment]
Hello Massimo,

I find the amount of functionality that you put in less than 150 lines of
code really amazing. Thanks for showing the power of python!

I'd like to take the opportunity to ask why there are two os.fork()
statements in the daemonize function.
Wouldn't something like the following be enough?
def daemonize(): if os.fork()==0: os.setsid() if os.fork()==0: return os.
_exit(0)

2014-10-16 15:52 GMT+02:00 mdipierro notifications@github.com:

**Comment by rogererens** [comment]
Sorry, pressed the wrong key combination, which sent of my previous message
prematurely.
I meant the content of daemonize could be something like:
my_pid = os.fork()
if my_pid == 0:
    os.setsid()
    return
os._exit(0)

?
Cheers,

Roger

2014-10-16 18:39 GMT+02:00 Roger Erens roger.erens@e-s-c.biz:

**Comment by mdipierro** [comment]
Thanks. 
I think you are right. I read somewhere that you need two forms to demonize safely but I think your approach should work.
I'd take a patch if you find it to work.

massimo

**Comment by rogererens** [comment]
Hi Massimo,
I'm not sure (in general) what daemonize is supposed to do, so I'll refrain from creating a PR for this and leave it to the experts :-)

**Pull request merged**
